In [1]:
import numpy as np

In [3]:
# Indexacion de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Extraccion de elementos en forma ascendente
x[2]

2

In [7]:
# Extraccion de elementos en forma descendente
x[-2]

8

In [9]:
x.shape = (2,5) #Conversion del arreglo a formato bidimentsional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
# Extraccion del elemento con el indice 1 en el renglon e indice 3 en columna
x[1,3]

8

In [13]:
# Alternativa de extraccion del elemento con indice 1 en renglon e indice 3 en columna
x[1][3]

8

In [15]:
# Extraccion del elemento con indice 1 en renglon y primer elemento en forma descendente
x[1,-1]

9

In [17]:
# Extraccion del renglon completo con indice 0 (al no especificar indice de columna)
x[0]

array([0, 1, 2, 3, 4])

In [21]:
# Cortes en arreglos
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2]  #Formato: "start:stop:step"

array([1, 3, 5])

In [23]:
# Corte del arreglo de adelante hacia atras, considerando dos elementos
x[-2:10] 

array([8, 9])

In [25]:
# Corte del arreglo de adelante hacia atras, iniciando tres posiciones a partir del final
# y retrocediendo hasta tener como limite el numero 3
x[-3:3:-1]

array([7, 6, 5, 4])

In [27]:
# Definicion de un nuevo arreglo
# Creacion de un arreglo en forma descendente - del 10 al 1 (sin incluirlo) - con decrementos 
x = np.arange(10,1,-1) 
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [29]:
# Extraccion de elementos especificos del arreglo
# Extraccion de elementos con incides 3,3,1,8
x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [31]:
# Extraccion de elementos con indices 3,3, -3 (descendente) y 8
x[np.array([3,3,-3,8])]

array([7, 7, 4, 2])

In [33]:
# Extraccion basada en pares
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [35]:
# Extraccion de "coordenadas" (0,0), (2,1) y (4,2)
y[np.array([0,2,4]),np.array([0,1,2])]

array([ 0, 15, 30])

In [37]:
# Union de arreglos
arr = np.concatenate(([1,2,3],[4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [39]:
# Apilado vertical de vectores
np.stack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# Concatenacion de matrices
mat_1 = np.array([[1,2,3],[4,5,6]])
mat_2 = np.array([[1,1,1],[2,2,2]])
np.concatenate((mat_1,mat_2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [45]:
np.concatenate((mat_1,mat_2), axis=1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])