In [1]:
import numpy as np
# Creacion de un arreglo a partir de una lista

lista1 = [1,2,3,4,5]
arreglo1 = np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [3]:
type(arreglo1)

numpy.ndarray

In [5]:
# Creacion de un arreglo a partir de una lista de listas
lista2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Las listas pueden contener diversos tipos de datos
lista = ["a",True,1]
lista

['a', True, 1]

In [9]:
# Los arreglos solo pueden tener un mismo tipo de datos
# Usan menos espacio en memoria
arreglo = np.array(lista)
arreglo # Solo se almacenaron textos

array(['a', 'True', '1'], dtype='<U21')

In [11]:
# Creacion de arreglos con ceros
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# Creacion de arreglos con numeros aleatorios uniformes entre 0 y 1
arreglo4 = np.random.random((3,2))
arreglo4

array([[0.47117689, 0.29169998],
       [0.33737882, 0.32792756],
       [0.22551357, 0.81001406]])

In [17]:
# Creacion de arreglos en un rango
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
# Ejercicio Generar un arreglo tri-dimensional random
arreglo1 = np.array([[1,2],
                    [5,7]])
arreglo2 = np.array([[8,9],
                    [5,7]])
arreglo3 = np.array([[1,2],
                    [5,7]])

arreglo3D = np.array([arreglo1,arreglo2,arreglo3])
arreglo3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [27]:
arreglo3 = np.zeros((5,4))
arreglo3.shape

(5, 4)

In [29]:
# Conversion de un arreglo multi-dimensional a uni-dimensional
lista2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]

arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Cambio de dimension de un arreglo

arreglo = np.array([[1,2],
                    [3,4],
                    [5,6]])

arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# Ejemplo de ERROR al momento de cambiar la dimension
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [45]:
#El Atributo dtype
np.array([1.25,2.63,200.88]).dtype

dtype('float64')

In [41]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).dtype

dtype('int64')

In [43]:
np.array(["Introduccion","a","la","programacion"]).dtype

dtype('<U12')

In [47]:
# Uso de dtype como argumento
np.array([1.25,2.63,200.88], dtype=np.float32).dtype

dtype('float32')

In [49]:
# Cambio de tipo de arreglo
arreglo_booleano = np.array([[True,False]], dtype=np.bool_)
arreglo_booleano.dtype

dtype('bool')

In [51]:
arreglo = arreglo_booleano.astype(np.int32)
arreglo

array([[1, 0]], dtype=int32)

In [53]:
# Homologacion del tipo por jerarquia

np.array([0,50,50.8]).dtype

dtype('float64')

In [55]:
np.array([False,42]).dtype

dtype('int64')