In [1]:
import numpy as np
lista = [1,2,3,4,5,6,7,8,9]
lista
arr = np.array(lista)

In [15]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

1

In [7]:
arr[0] + arr[6]

8

In [9]:
matriz[0]

array([1, 2, 3])

In [11]:
matriz[0][2]

3

In [19]:
matriz[0,2]

3

In [23]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [25]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [27]:
arr[4:]

array([5, 6, 7, 8, 9])

In [29]:
arr[::3]

array([1, 4, 7])

In [31]:
arr[-1]

9

In [33]:
arr[-3]

7

In [37]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])