In [3]:
import numpy as np
arr = np.random.randint(1,10,(3,2))

In [7]:
arr.shape

(3, 2)

In [9]:
arr

array([[3, 1],
       [2, 6],
       [4, 7]])

In [11]:
arr.reshape(1,6)

array([[3, 1, 2, 6, 4, 7]])

In [13]:
arr.reshape(2,3)

array([[3, 1, 2],
       [6, 4, 7]])

In [15]:
np.reshape(arr,(1,6))

array([[3, 1, 2, 6, 4, 7]])

In [17]:
np.reshape(arr,(2,3),"C")

array([[3, 1, 2],
       [6, 4, 7]])