In [9]:
import numpy as np

#Ejercicio 1
array1 = np.array([12,13,14,15,16,17,18,19,20])
np.flip(array1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

In [15]:
# Ejercicio 2
fahrenheit = np.array([0.,12.,45.21,99.91,32])
centigrados = (5 * (fahrenheit - 32)) / 9
centigrados

array([-17.77777778, -11.11111111,   7.33888889,  37.72777778,
         0.        ])

In [23]:
# Ejercicio 3
array_1 = np.array([0,10,20])
array_2 = np.array([20,10,30])

new_arr = np.unique(np.concatenate((array_1,array_2)))
new_arr

array([ 0, 10, 20, 30])